name: 🚀 Publish to npm
on:
  release:
    types: [published]

env:
  NODE_VERSION: "18.x"

jobs:
  release:
    name: 🆕 Release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v3
      - name: 🟢 node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: "https://registry.npmjs.org/"
          cache: npm
      - name: 📦 npm ci
        run: npm ci

      - name: 🚧 Run build
        run: npm run build

      - name: 🎉 Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
